const ROLES = {
    CUSTOMER: 'CUSTOMER',
    MANAGER: 'MANAGER',
    DELIVERY: 'DELIVERY',
    ADMIN: 'ADMIN',
};

const ORDER_STATES = {
    PLACED: 'PLACED',
    PENDING_MANAGER: 'PENDING_MANAGER',

    REJECTED_BY_MANAGER: 'REJECTED_BY_MANAGER',
    CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',

    ACCEPTED: 'ACCEPTED',
    RESERVED: 'RESERVED',

    ASSIGNING: 'ASSIGNING',
    ASSIGNED: 'ASSIGNED',

    PICKED_UP: 'PICKED_UP',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',

    DELIVERED: 'DELIVERED',
    FAILED_DELIVERY: 'FAILED_DELIVERY',

    COD_PENDING: 'COD_PENDING',
    COD_SETTLED: 'COD_SETTLED',

    CLOSED: 'CLOSED',
};

module.exports = {
    ROLES,
    ORDER_STATES,
};
